// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: transport/internet/xproto/config.proto

package xproto

import (
	reality "github.com/xtls/xray-core/transport/internet/reality"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Config is the xproto transport configuration. It embeds a REALITY config
// (so the handshake is REALITY-compatible) and adds a private dest pool
// extension used by the server to rotate the fallback target per connection.
type Config struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Base  *reality.Config        `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	// Private extension: dest pool. When non-empty, the server picks one dest
	// per accepted connection (random) for the REALITY fallback target, instead
	// of the fixed base.dest. The client ignores this field.
	Dests []string `protobuf:"bytes,2,rep,name=dests,proto3" json:"dests,omitempty"`
	// Private extension: handshake padding scheme. When enabled, both sides
	// exchange a one-time random-length padding right after the REALITY
	// handshake to blur the first application packet's length signature.
	// Continuous traffic morphing is left to the VLESS/Vision layer.
	Padding       *PaddingScheme `protobuf:"bytes,3,opt,name=padding,proto3" json:"padding,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Config) Reset() {
	*x = Config{}
	mi := &file_transport_internet_xproto_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config) ProtoMessage() {}

func (x *Config) ProtoReflect() protoreflect.Message {
	mi := &file_transport_internet_xproto_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config.ProtoReflect.Descriptor instead.
func (*Config) Descriptor() ([]byte, []int) {
	return file_transport_internet_xproto_config_proto_rawDescGZIP(), []int{0}
}

func (x *Config) GetBase() *reality.Config {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *Config) GetDests() []string {
	if x != nil {
		return x.Dests
	}
	return nil
}

func (x *Config) GetPadding() *PaddingScheme {
	if x != nil {
		return x.Padding
	}
	return nil
}

type PaddingScheme struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enabled       bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	MinLen        uint32                 `protobuf:"varint,2,opt,name=min_len,json=minLen,proto3" json:"min_len,omitempty"`
	MaxLen        uint32                 `protobuf:"varint,3,opt,name=max_len,json=maxLen,proto3" json:"max_len,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaddingScheme) Reset() {
	*x = PaddingScheme{}
	mi := &file_transport_internet_xproto_config_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaddingScheme) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaddingScheme) ProtoMessage() {}

func (x *PaddingScheme) ProtoReflect() protoreflect.Message {
	mi := &file_transport_internet_xproto_config_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaddingScheme.ProtoReflect.Descriptor instead.
func (*PaddingScheme) Descriptor() ([]byte, []int) {
	return file_transport_internet_xproto_config_proto_rawDescGZIP(), []int{1}
}

func (x *PaddingScheme) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *PaddingScheme) GetMinLen() uint32 {
	if x != nil {
		return x.MinLen
	}
	return 0
}

func (x *PaddingScheme) GetMaxLen() uint32 {
	if x != nil {
		return x.MaxLen
	}
	return 0
}

var File_transport_internet_xproto_config_proto protoreflect.FileDescriptor

const file_transport_internet_xproto_config_proto_rawDesc = "" +
	"\n" +
	"&transport/internet/xproto/config.proto\x12\x1exray.transport.internet.xproto\x1a'transport/internet/reality/config.proto\"\xa4\x01\n" +
	"\x06Config\x12;\n" +
	"\x04base\x18\x01 \x01(\v2'.xray.transport.internet.reality.ConfigR\x04base\x12\x14\n" +
	"\x05dests\x18\x02 \x03(\tR\x05dests\x12G\n" +
	"\apadding\x18\x03 \x01(\v2-.xray.transport.internet.xproto.PaddingSchemeR\apadding\"[\n" +
	"\rPaddingScheme\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12\x17\n" +
	"\amin_len\x18\x02 \x01(\rR\x06minLen\x12\x17\n" +
	"\amax_len\x18\x03 \x01(\rR\x06maxLenB|\n" +
	"\"com.xray.transport.internet.xprotoP\x01Z3github.com/xtls/xray-core/transport/internet/xproto\xaa\x02\x1eXray.Transport.Internet.Xprotob\x06proto3"

var (
	file_transport_internet_xproto_config_proto_rawDescOnce sync.Once
	file_transport_internet_xproto_config_proto_rawDescData []byte
)

func file_transport_internet_xproto_config_proto_rawDescGZIP() []byte {
	file_transport_internet_xproto_config_proto_rawDescOnce.Do(func() {
		file_transport_internet_xproto_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_transport_internet_xproto_config_proto_rawDesc), len(file_transport_internet_xproto_config_proto_rawDesc)))
	})
	return file_transport_internet_xproto_config_proto_rawDescData
}

var file_transport_internet_xproto_config_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_transport_internet_xproto_config_proto_goTypes = []any{
	(*Config)(nil),         // 0: xray.transport.internet.xproto.Config
	(*PaddingScheme)(nil),  // 1: xray.transport.internet.xproto.PaddingScheme
	(*reality.Config)(nil), // 2: xray.transport.internet.reality.Config
}
var file_transport_internet_xproto_config_proto_depIdxs = []int32{
	2, // 0: xray.transport.internet.xproto.Config.base:type_name -> xray.transport.internet.reality.Config
	1, // 1: xray.transport.internet.xproto.Config.padding:type_name -> xray.transport.internet.xproto.PaddingScheme
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_transport_internet_xproto_config_proto_init() }
func file_transport_internet_xproto_config_proto_init() {
	if File_transport_internet_xproto_config_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_transport_internet_xproto_config_proto_rawDesc), len(file_transport_internet_xproto_config_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_transport_internet_xproto_config_proto_goTypes,
		DependencyIndexes: file_transport_internet_xproto_config_proto_depIdxs,
		MessageInfos:      file_transport_internet_xproto_config_proto_msgTypes,
	}.Build()
	File_transport_internet_xproto_config_proto = out.File
	file_transport_internet_xproto_config_proto_goTypes = nil
	file_transport_internet_xproto_config_proto_depIdxs = nil
}
