// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: app/dynconfig/command/command.proto

package command

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetDestPoolRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDestPoolRequest) Reset() {
	*x = GetDestPoolRequest{}
	mi := &file_app_dynconfig_command_command_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDestPoolRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDestPoolRequest) ProtoMessage() {}

func (x *GetDestPoolRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_dynconfig_command_command_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDestPoolRequest.ProtoReflect.Descriptor instead.
func (*GetDestPoolRequest) Descriptor() ([]byte, []int) {
	return file_app_dynconfig_command_command_proto_rawDescGZIP(), []int{0}
}

type GetDestPoolResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DestPool      []string               `protobuf:"bytes,1,rep,name=dest_pool,json=destPool,proto3" json:"dest_pool,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDestPoolResponse) Reset() {
	*x = GetDestPoolResponse{}
	mi := &file_app_dynconfig_command_command_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDestPoolResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDestPoolResponse) ProtoMessage() {}

func (x *GetDestPoolResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_dynconfig_command_command_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDestPoolResponse.ProtoReflect.Descriptor instead.
func (*GetDestPoolResponse) Descriptor() ([]byte, []int) {
	return file_app_dynconfig_command_command_proto_rawDescGZIP(), []int{1}
}

func (x *GetDestPoolResponse) GetDestPool() []string {
	if x != nil {
		return x.DestPool
	}
	return nil
}

type SetDestPoolRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DestPool      []string               `protobuf:"bytes,1,rep,name=dest_pool,json=destPool,proto3" json:"dest_pool,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetDestPoolRequest) Reset() {
	*x = SetDestPoolRequest{}
	mi := &file_app_dynconfig_command_command_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetDestPoolRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetDestPoolRequest) ProtoMessage() {}

func (x *SetDestPoolRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_dynconfig_command_command_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetDestPoolRequest.ProtoReflect.Descriptor instead.
func (*SetDestPoolRequest) Descriptor() ([]byte, []int) {
	return file_app_dynconfig_command_command_proto_rawDescGZIP(), []int{2}
}

func (x *SetDestPoolRequest) GetDestPool() []string {
	if x != nil {
		return x.DestPool
	}
	return nil
}

type SetDestPoolResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetDestPoolResponse) Reset() {
	*x = SetDestPoolResponse{}
	mi := &file_app_dynconfig_command_command_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetDestPoolResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetDestPoolResponse) ProtoMessage() {}

func (x *SetDestPoolResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_dynconfig_command_command_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetDestPoolResponse.ProtoReflect.Descriptor instead.
func (*SetDestPoolResponse) Descriptor() ([]byte, []int) {
	return file_app_dynconfig_command_command_proto_rawDescGZIP(), []int{3}
}

type Config struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Config) Reset() {
	*x = Config{}
	mi := &file_app_dynconfig_command_command_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config) ProtoMessage() {}

func (x *Config) ProtoReflect() protoreflect.Message {
	mi := &file_app_dynconfig_command_command_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config.ProtoReflect.Descriptor instead.
func (*Config) Descriptor() ([]byte, []int) {
	return file_app_dynconfig_command_command_proto_rawDescGZIP(), []int{4}
}

var File_app_dynconfig_command_command_proto protoreflect.FileDescriptor

const file_app_dynconfig_command_command_proto_rawDesc = "" +
	"\n" +
	"#app/dynconfig/command/command.proto\x12\x1fxray.core.app.dynconfig.command\"\x14\n" +
	"\x12GetDestPoolRequest\"2\n" +
	"\x13GetDestPoolResponse\x12\x1b\n" +
	"\tdest_pool\x18\x01 \x03(\tR\bdestPool\"1\n" +
	"\x12SetDestPoolRequest\x12\x1b\n" +
	"\tdest_pool\x18\x01 \x03(\tR\bdestPool\"\x15\n" +
	"\x13SetDestPoolResponse\"\b\n" +
	"\x06Config2\x8a\x02\n" +
	"\x10DynConfigService\x12z\n" +
	"\vGetDestPool\x123.xray.core.app.dynconfig.command.GetDestPoolRequest\x1a4.xray.core.app.dynconfig.command.GetDestPoolResponse\"\x00\x12z\n" +
	"\vSetDestPool\x123.xray.core.app.dynconfig.command.SetDestPoolRequest\x1a4.xray.core.app.dynconfig.command.SetDestPoolResponse\"\x00Bz\n" +
	"#com.xray.core.app.dynconfig.commandP\x01Z/github.com/xtls/xray-core/app/dynconfig/command\xaa\x02\x1fXray.Core.App.Dynconfig.Commandb\x06proto3"

var (
	file_app_dynconfig_command_command_proto_rawDescOnce sync.Once
	file_app_dynconfig_command_command_proto_rawDescData []byte
)

func file_app_dynconfig_command_command_proto_rawDescGZIP() []byte {
	file_app_dynconfig_command_command_proto_rawDescOnce.Do(func() {
		file_app_dynconfig_command_command_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_app_dynconfig_command_command_proto_rawDesc), len(file_app_dynconfig_command_command_proto_rawDesc)))
	})
	return file_app_dynconfig_command_command_proto_rawDescData
}

var file_app_dynconfig_command_command_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_app_dynconfig_command_command_proto_goTypes = []any{
	(*GetDestPoolRequest)(nil),  // 0: xray.core.app.dynconfig.command.GetDestPoolRequest
	(*GetDestPoolResponse)(nil), // 1: xray.core.app.dynconfig.command.GetDestPoolResponse
	(*SetDestPoolRequest)(nil),  // 2: xray.core.app.dynconfig.command.SetDestPoolRequest
	(*SetDestPoolResponse)(nil), // 3: xray.core.app.dynconfig.command.SetDestPoolResponse
	(*Config)(nil),              // 4: xray.core.app.dynconfig.command.Config
}
var file_app_dynconfig_command_command_proto_depIdxs = []int32{
	0, // 0: xray.core.app.dynconfig.command.DynConfigService.GetDestPool:input_type -> xray.core.app.dynconfig.command.GetDestPoolRequest
	2, // 1: xray.core.app.dynconfig.command.DynConfigService.SetDestPool:input_type -> xray.core.app.dynconfig.command.SetDestPoolRequest
	1, // 2: xray.core.app.dynconfig.command.DynConfigService.GetDestPool:output_type -> xray.core.app.dynconfig.command.GetDestPoolResponse
	3, // 3: xray.core.app.dynconfig.command.DynConfigService.SetDestPool:output_type -> xray.core.app.dynconfig.command.SetDestPoolResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_app_dynconfig_command_command_proto_init() }
func file_app_dynconfig_command_command_proto_init() {
	if File_app_dynconfig_command_command_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_app_dynconfig_command_command_proto_rawDesc), len(file_app_dynconfig_command_command_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_app_dynconfig_command_command_proto_goTypes,
		DependencyIndexes: file_app_dynconfig_command_command_proto_depIdxs,
		MessageInfos:      file_app_dynconfig_command_command_proto_msgTypes,
	}.Build()
	File_app_dynconfig_command_command_proto = out.File
	file_app_dynconfig_command_command_proto_goTypes = nil
	file_app_dynconfig_command_command_proto_depIdxs = nil
}
