// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v6.33.5
// source: app/dynconfig/command/command.proto

package command

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DynConfigService_GetDestPool_FullMethodName = "/xray.core.app.dynconfig.command.DynConfigService/GetDestPool"
	DynConfigService_SetDestPool_FullMethodName = "/xray.core.app.dynconfig.command.DynConfigService/SetDestPool"
)

// DynConfigServiceClient is the client API for DynConfigService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DynConfigServiceClient interface {
	GetDestPool(ctx context.Context, in *GetDestPoolRequest, opts ...grpc.CallOption) (*GetDestPoolResponse, error)
	SetDestPool(ctx context.Context, in *SetDestPoolRequest, opts ...grpc.CallOption) (*SetDestPoolResponse, error)
}

type dynConfigServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDynConfigServiceClient(cc grpc.ClientConnInterface) DynConfigServiceClient {
	return &dynConfigServiceClient{cc}
}

func (c *dynConfigServiceClient) GetDestPool(ctx context.Context, in *GetDestPoolRequest, opts ...grpc.CallOption) (*GetDestPoolResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDestPoolResponse)
	err := c.cc.Invoke(ctx, DynConfigService_GetDestPool_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dynConfigServiceClient) SetDestPool(ctx context.Context, in *SetDestPoolRequest, opts ...grpc.CallOption) (*SetDestPoolResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetDestPoolResponse)
	err := c.cc.Invoke(ctx, DynConfigService_SetDestPool_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DynConfigServiceServer is the server API for DynConfigService service.
// All implementations must embed UnimplementedDynConfigServiceServer
// for forward compatibility.
type DynConfigServiceServer interface {
	GetDestPool(context.Context, *GetDestPoolRequest) (*GetDestPoolResponse, error)
	SetDestPool(context.Context, *SetDestPoolRequest) (*SetDestPoolResponse, error)
	mustEmbedUnimplementedDynConfigServiceServer()
}

// UnimplementedDynConfigServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDynConfigServiceServer struct{}

func (UnimplementedDynConfigServiceServer) GetDestPool(context.Context, *GetDestPoolRequest) (*GetDestPoolResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDestPool not implemented")
}
func (UnimplementedDynConfigServiceServer) SetDestPool(context.Context, *SetDestPoolRequest) (*SetDestPoolResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetDestPool not implemented")
}
func (UnimplementedDynConfigServiceServer) mustEmbedUnimplementedDynConfigServiceServer() {}
func (UnimplementedDynConfigServiceServer) testEmbeddedByValue()                          {}

// UnsafeDynConfigServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DynConfigServiceServer will
// result in compilation errors.
type UnsafeDynConfigServiceServer interface {
	mustEmbedUnimplementedDynConfigServiceServer()
}

func RegisterDynConfigServiceServer(s grpc.ServiceRegistrar, srv DynConfigServiceServer) {
	// If the following call panics, it indicates UnimplementedDynConfigServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DynConfigService_ServiceDesc, srv)
}

func _DynConfigService_GetDestPool_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDestPoolRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DynConfigServiceServer).GetDestPool(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DynConfigService_GetDestPool_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DynConfigServiceServer).GetDestPool(ctx, req.(*GetDestPoolRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DynConfigService_SetDestPool_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetDestPoolRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DynConfigServiceServer).SetDestPool(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DynConfigService_SetDestPool_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DynConfigServiceServer).SetDestPool(ctx, req.(*SetDestPoolRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DynConfigService_ServiceDesc is the grpc.ServiceDesc for DynConfigService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DynConfigService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "xray.core.app.dynconfig.command.DynConfigService",
	HandlerType: (*DynConfigServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetDestPool",
			Handler:    _DynConfigService_GetDestPool_Handler,
		},
		{
			MethodName: "SetDestPool",
			Handler:    _DynConfigService_SetDestPool_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "app/dynconfig/command/command.proto",
}
