// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: app/dynconfig/config.proto

package dynconfig

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Config is the configuration for the DynConfig app. It seeds the initial
// dynamic parameters; subsequent updates happen at runtime via commander.
type Config struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Initial dest pool. The xproto server rotates through these for the
	// REALITY fallback target.
	DestPool      []string `protobuf:"bytes,1,rep,name=dest_pool,json=destPool,proto3" json:"dest_pool,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Config) Reset() {
	*x = Config{}
	mi := &file_app_dynconfig_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config) ProtoMessage() {}

func (x *Config) ProtoReflect() protoreflect.Message {
	mi := &file_app_dynconfig_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config.ProtoReflect.Descriptor instead.
func (*Config) Descriptor() ([]byte, []int) {
	return file_app_dynconfig_config_proto_rawDescGZIP(), []int{0}
}

func (x *Config) GetDestPool() []string {
	if x != nil {
		return x.DestPool
	}
	return nil
}

// DestPoolRequest is the commander request payload to replace the dest pool.
type DestPoolRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DestPool      []string               `protobuf:"bytes,1,rep,name=dest_pool,json=destPool,proto3" json:"dest_pool,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DestPoolRequest) Reset() {
	*x = DestPoolRequest{}
	mi := &file_app_dynconfig_config_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DestPoolRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DestPoolRequest) ProtoMessage() {}

func (x *DestPoolRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_dynconfig_config_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DestPoolRequest.ProtoReflect.Descriptor instead.
func (*DestPoolRequest) Descriptor() ([]byte, []int) {
	return file_app_dynconfig_config_proto_rawDescGZIP(), []int{1}
}

func (x *DestPoolRequest) GetDestPool() []string {
	if x != nil {
		return x.DestPool
	}
	return nil
}

var File_app_dynconfig_config_proto protoreflect.FileDescriptor

const file_app_dynconfig_config_proto_rawDesc = "" +
	"\n" +
	"\x1aapp/dynconfig/config.proto\x12\x17xray.core.app.dynconfig\"%\n" +
	"\x06Config\x12\x1b\n" +
	"\tdest_pool\x18\x01 \x03(\tR\bdestPool\".\n" +
	"\x0fDestPoolRequest\x12\x1b\n" +
	"\tdest_pool\x18\x01 \x03(\tR\bdestPoolBX\n" +
	"\x16com.xray.app.dynconfigP\x01Z'github.com/xtls/xray-core/app/dynconfig\xaa\x02\x12Xray.App.Dynconfigb\x06proto3"

var (
	file_app_dynconfig_config_proto_rawDescOnce sync.Once
	file_app_dynconfig_config_proto_rawDescData []byte
)

func file_app_dynconfig_config_proto_rawDescGZIP() []byte {
	file_app_dynconfig_config_proto_rawDescOnce.Do(func() {
		file_app_dynconfig_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_app_dynconfig_config_proto_rawDesc), len(file_app_dynconfig_config_proto_rawDesc)))
	})
	return file_app_dynconfig_config_proto_rawDescData
}

var file_app_dynconfig_config_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_app_dynconfig_config_proto_goTypes = []any{
	(*Config)(nil),          // 0: xray.core.app.dynconfig.Config
	(*DestPoolRequest)(nil), // 1: xray.core.app.dynconfig.DestPoolRequest
}
var file_app_dynconfig_config_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_app_dynconfig_config_proto_init() }
func file_app_dynconfig_config_proto_init() {
	if File_app_dynconfig_config_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_app_dynconfig_config_proto_rawDesc), len(file_app_dynconfig_config_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_app_dynconfig_config_proto_goTypes,
		DependencyIndexes: file_app_dynconfig_config_proto_depIdxs,
		MessageInfos:      file_app_dynconfig_config_proto_msgTypes,
	}.Build()
	File_app_dynconfig_config_proto = out.File
	file_app_dynconfig_config_proto_goTypes = nil
	file_app_dynconfig_config_proto_depIdxs = nil
}
